### ISSUE TITLE
Huge battery drain on Lollipop

### ISSUE THREAD

**Issue by tntodorov** [haiwen/seadroid#314] opened 2015-04-02 09:52 UTC
Hello,

I have been using Seafile for a while, both on desktop and mobile platforms. On mobile I have it running on a Samsung Galaxy S3 phone with Android 4.3, and on a Google Nexus 10 tablet now running Lollipop 5.1.  I have no problems with the Galaxy running the older Android, but I noticed major increase in battery drain on the tablet with Lollipop - please see the attached screenshot. Since the upgrade to Lollipop, Seafile has been constantly and consistently the top battery "eater", where before that the screen and the Android OS were both at the top on any of my devices.

Here is a screenshot of my Nexus 10 battery stats:
![seadroid battery usage](https://cloud.githubusercontent.com/assets/9284623/6961646/09588766-d8fb-11e4-9e6f-8955b0809cd3.png)

I am using Seafile 1.5.1. I do not have automatic camera upload enabled on the tablet, and it is a Wifi-only device, so no 2g/3g/4g connectivity is available there at all. My server is version 3.1.7, if that is relevant.

I am willing to follow up with more information if any is required and do any reasonable tests if asked.

Best regards,

~tntodorov

**Comment by Logan676** [comment] 2015-04-02 13:59
Thanks for your feedback. Here are some clues for your reference.

* Since Seafile theme is total white, it may cost more battery power if you keep it at the foreground for a long period of time.
* There are three services running at background, including camera upload service, files transferring service and data monitor service. Did you download or upload files by the way?
* The file list keep refreshing every second when visible, if that\`s the case, leave it background and watch the battery consumptions.

**Comment by tntodorov** [comment] 2015-04-02 14:55
Actually, I have not opened Seafile for weeks, so it is only the background service that is using up the battery. I also have not changed more than 2-3 files per week on the server from any other client. As I mentioned in the initial post, automatic camera uploads on the tablet are disabled, but I have downloaded files from my server immediately after I installed the app on the tablet. It is mainly e-books and PDF datasheets of electronic components and these types of files do not change once they are uploaded to the server and any other client - they are not working documents like from Word or Excel, etc. The info in the app's Settings screen is telling me that the local cache is 1.7G. I look up and open the downloaded files from ES File Explorer, not from the Seafile client.

What I forgot to mention is that with this battery usage my tablet lasts less than 12 hrs, where before the upgrade to Lollipop it lasted close to 2 days. My usage patterns haven't changes, so why would Seafile on the same tablet using KitKat 4.4.2 be way down the list in the battery stats, but jump way to the very top after the Android upgrade? Is there any reasonable circumstance that would account for Seafile alone using a third of the whole battery budget of my device?

**Comment by Logan676** [comment] 2015-04-07 03:06
> Is there any reasonable circumstance that would account for Seafile alone using a third of the whole battery budget of my device?  

I am afraid not, actually we didn\`t introduce any features specifically for Android Lollipop. Does it still on the very top of the battery stats list now? I tend to think this may caused by the OS upgrade.

**Closed** 2015-04-14 10:30 UTC
