### ISSUE TITLE
SSL issue if using Cloudflare Proxy with TLS 1.3

### ISSUE THREAD

**Issue by Florian-Sabonchi** [haiwen/seadroid#915] opened 2021-11-02 14:32 UTC
![IMG_20211102_152743_345.jpg](https://user-images.githubusercontent.com/54689374/139866848-0ff376fb-e512-4ce4-9f44-190c062a8ff5.jpg)

**Comment by louisroyer** [comment] 2021-11-07 11:14
I think this issue is a duplicate of #890.

**Comment by Florian-Sabonchi** [comment] 2021-11-07 17:36
> I think this issue is a duplicate of #890.

Closed

**Closed** 2021-11-07 17:36 UTC
