### ISSUE TITLE
Automatic image upload broken

### ISSUE THREAD

**Issue by nazco** [haiwen/seadroid#800] opened 2019-04-07 09:58 UTC
The automatic image upload isn't working anymore. I used the feature a few years now but in the last months it got more and more broken. In the beginning the upload was delayed up to a day, but now the automatic upload dosn't work anymore for me. I use an android 8.0 phone with the latest version 2.2.14 from f-droid but the problem persist also with the version from the play store.

I've tried to fix it by reinstalling the app multiple times but that doesn't help.

**Comment by freeplant** [comment] 2019-04-07 11:24
How many photos do you have?

**Comment by nazco** [comment] 2019-04-08 10:59
Currently about 2.5k

**Comment by nazco** [comment] 2019-04-17 07:08
Maybe this problem is related to the changes introduced with this commit: https://github.com/haiwen/seadroid/commit/e1d67ae972d3363cbce7d073257c7a9ad1653b56

**Comment by sosnicki** [comment] 2019-05-09 08:28
Hi, I confirm that the automatic upload is not working. The synchronization starts when the application is opened.

**Comment by freeplant** [comment] 2019-05-09 08:52
@sosnicki I don't understand what do you mean by "not working".

From the description, "the synchronization starts when the application is opened", it means the feature can work.

**Comment by sosnicki** [comment] 2019-05-09 09:00
Ok, I'm sory, I'll try to explain. When I take a photo, it isn't sent to the server right away. It is uploaded only when I open Seafile application. It seems like, the start of the application triggers synchronization process.

**Comment by Cisco30** [comment] 2019-05-09 09:02
In fact it means that the application does not work in the background.  We do not have to open the app for the upload to work.  I do not have this problem with the latest version.

**Comment by sosnicki** [comment] 2019-05-09 09:24
I've installed the latest version 2.2.15. I've took two photos and I've waited for a 5 minutes and the photos weren't sent to the server. I've checked last synchronization time in Settings->Synchronization->Seafile and the time is older then the time of taking photos. I think it means that taking a photos doesn't start  synchronization. I've set 3 folders for synchronization (Camera, Hangout, WhatApp) in the Seafile settings, maybe it's an issue?

**Comment by freeplant** [comment] 2019-05-09 09:27
We use Android system's synchronization framework to schedule the photo upload. The default interval is 10 minutes. If you want to start synchronization soon, you can click the syncing now in "Settings->Synchronization->Seafile"

**Comment by sosnicki** [comment] 2019-05-09 09:44
Thank you very much for the tip! 

I have Xiaomi with MIUI and it didn't synchronize this app for days because of energy saving settings. I've changed battery save mode to 'No limit' and enabled the 'Autostart' and it works like a charm. A few seconds after the photo is taken, it is sent to the server. 

Maybe @nazco has the same problem.

**Comment by nazco** [comment] 2019-05-09 10:38
Nope, seems to be another issue. But I debugged it a little more after your suggestions. There is no sync of images at all, even if I trigger a manual sync like @freeplant suggested. But, if I chose a new album, the folder of this album is synced but without any containing images.

**Comment by sosnicki** [comment] 2019-05-09 10:51
Maybe something is wrong with the image format/extension? If you attach some example photo, I can check it with my app and server.

**Comment by nazco** [comment] 2019-05-09 11:07
I'm quite sure it isn't the format or extension. Why should the default camera app change the format? I'll add images later if still needed.

**Comment by TT-SWP13** [comment] 2019-05-10 07:47
@sosnicki I also have a Xiaomi wit MIUI 10. I tested also with MUIU 9 and all Versions of Seadroid from 2.2.8 to 2.2.15. With Server-Version 6.3.4 and App-Version 2.2.8 it works for me on my phone. But not with newer versions. I do not know why. I have enabled android sync, disabled all energy savings, give the app all permissions (WiFi, mobile Data, files, ...)  and try manually sync. But nothing works. It could be my nginx security settings. But the clients on Linux and Windows worked great.

On local network (with server-IP) it doesn't work either .

**Comment by nazco** [comment] 2019-05-10 08:21
Maybe this was the version the problems started for me. But I'm not that sure. Could match the timing it started to be buggy.

**Comment by nazco** [comment] 2019-05-14 18:28
I've set the power options suggested by @sosnicki a few days ago. It didn't work directly, but now it seems to work again. I think maybe the app tried to index all the images but was interrupted before by the garbage collector. Now it isn't interrupted while running in the background and could finish the work. @freeplant could this be a explanation?

**Comment by arnstads** [comment] 2019-05-20 10:49
For me it's also not working. 
Running version 2.2.14 on a Huawei P20 with Android 8.0.0 and EMUI user interface.
It seems that nothing happens if I activate the photo sync and take pictures. Neither waiting for a long time or sync manually. The transfer list is also empty.

**Comment by nazco** [comment] 2019-05-20 10:55
A day after my last comment I got an update to Android 9. Now it isn't working again. Same problem as before.

**Comment by cyrilEngelaere** [comment] 2019-06-06 09:36
+1

**Comment by bertvandepoel** [comment] 2019-06-22 13:20
I get this problem all the time. I just checked now and it hadn't synced since March. I'm on the latest version. I got it syncing again by disabling and reenabling syncing, but then of course as described in #815 it reuploads all deleted images. It's really quite weird and inconvenient that this works fine on Dropbox but not on Seafile, I switched to Seafile because I wanted to move away from proprietary commercial software like Dropbox but Seadroid is proving a struggle. The server and client are great though, love them :)

**Comment by framps** [comment] 2019-08-04 13:45
I use the auto sync feature on my mobile for a long time already. I had some trouble [first](https://forum.seafile.com/t/photo-upload-doesnt-start-on-android/338/5) 2 but finally got it working. 

I now have Android 8.0 (Orio) and also another new mobile with Android 9.0 (Pie). Autosync worked on Orio but stopped working a couple of weeks ago. On Pie I configured the autosync as on the Orio mobile but didin’t get it autostart. On both systems manual sync works fine. 

Mobile running Orio is a Samsung S7 which got some Android updates recently. May be there was some update causing the automatic sync to stop and this update was already rolled in into Pie?

Seafile Android client version: 2.2.18
Seafile Server: 6.2.5

**Comment by freeplant** [comment] 2019-08-05 04:32
The auto-back feature is working on my phone. Can you check "system -> accounts" to check whether sync feature of Seafile is turned on? Then can you open Seafile for 10 minutes, then check the transfer list to see if photos are being uploaded?

**Comment by framps** [comment] 2019-08-05 09:57
I attached a screenshot of my Samsung S7 running Orio (Android 8.0) when I selected  `system -> Cloud and accounts -> Accounts -> <seafile account> -> Sync account`

**Additional note:** On the `Accounts` page there is a slider called `Auto sync data` at the bottom which is turned on. 

![Screenshot_20190805-111113_Settings_red](https://user-images.githubusercontent.com/10913438/62453994-c83be000-b773-11e9-922b-cb96a142f0ab.jpg)

There is no automatic sync triggered when I wait for > 10 mins.

Frankly I think this may be an issue with power saving on Android. 
But power monitoring for Seafile is disabled with `system -> Device management -> Battery -> Unmonitored Apps` 

![Screenshot_20190805-113559_Device maintenance](https://user-images.githubusercontent.com/10913438/62454952-9f1c4f00-b775-11e9-89d1-d71efa890f4f.jpg)

**Comment by nazco** [comment] 2019-08-05 10:02
Same here, the sync doesn't start and if I start it manually it doesn't work too. Battery saving is also disabled for seafile.

**Comment by bertvandepoel** [comment] 2019-08-05 11:48
I did some experiments. When I trigger a "Sync Now" in the settings menu it used to sometimes succeed. Nowadays it doesn't at all (no fully succesful sync since March). I've found that when I deleted a lot of older images and videos from my phone, it started working again (not full succesful sync, but some images came through). It seems that Android's sync function has difficulty with large amounts of images or videos (or is that already passed on to the Seafile code and does it fail there)? To be clear, I'm talking about old images that have already been synced. The amount of new images was actually rather limited.

**Comment by nazco** [comment] 2019-08-05 11:56
@bertvandepoel that fits my obervations too. It seems to get worse with more images on the phone.

**Comment by framps** [comment] 2019-08-05 13:11
> Same here, the sync doesn't start and if I start it manually it doesn't work too. Battery saving is also disabled for seafile.

That's different to my observations: Manual sync works fine. It's just autosync isn't triggered.

**Comment by nazco** [comment] 2019-08-05 13:30
> That's different to my observations: Manual sync works fine. It's just autosync isn't triggered

Oh ok... How many Images do you have on your phone that should get synced?

**Comment by framps** [comment] 2019-08-05 15:39
For my tests it was one image only all the time but worked with > 10 files before. Total size of images is 3.9G (1216 file). They are stored on an external SD card.

**Comment by framps** [comment] 2019-08-08 21:50
@freeplant Are there any plans to work on this issue or is somebody working on this issue already? This issue is >= 4 months old :wink: I understand it's not an easy issue because of the huge number of Android Releases and possible settings. 
Just let me know which debug information I should provide to make progress.

**Comment by freeplant** [comment] 2019-08-09 02:43
We are working on the issue.

Actually we had already added a fix to the problem a few months ago. But it seems not fix the problem.

**Comment by framps** [comment] 2019-08-09 07:59
Great. :+1: Please let me know If I can help testing with my Samsung S7 running Android 8.0 and Samsung A20 running Android 9.0

**Comment by freeplant** [comment] 2019-08-27 02:06
We have prepared a package with logs: https://download.seafile.com/f/694c97bec5a94b45bb8f/?dl=1 .  The log is in /storage/emulated/0/seafile/seafileLog.txt   . Please send us the log when you have the problem.

**Comment by bertvandepoel** [comment] 2019-09-14 22:15
@freeplant I just found some time to give it a shot. I think however that the log might not be too useful in this case (it's just the same message over and over again). 

I've installed the new app version. Opened it, closed it, then left it open. Then several times forced the "sync now" feature under the synchronisation settings in Android. I always got the message "Sync is currently experiencing problems. It will be back shortly" and I haven't been able to do a full sync since March. In July I deleted a bunch of photos and forced sync now for a long time and then got some photos syncet, but it remains a problem, probably because of the size of my gallery. After trying for some time, I collected this log file:

[seafileLog.txt](https://github.com/haiwen/seadroid/files/3613187/seafileLog.txt)

**Comment by maxiaoping** [comment] 2019-09-23 17:28
> Great. 👍 Please let me know If I can help testing with my Samsung S7 running Android 8.0 and Samsung A20 running Android 9.0
Samsung  

> Great. 👍 Please let me know If I can help testing with my Samsung S7 running Android 8.0 and Samsung A20 running Android 9.0

You need to turn on the auto-start switch

**Comment by maxiaoping** [comment] 2019-09-23 17:35
![WechatIMG216](https://user-images.githubusercontent.com/7161204/65448267-021f8d80-de6b-11e9-9d07-9387870fa3da.jpeg)
The phone needs to open an app  auto-start switch

**Comment by bertvandepoel** [comment] 2019-09-23 17:36
@maxiaoping Is this a response to me or to @framps ?

**Comment by maxiaoping** [comment] 2019-09-23 17:38
![WechatIMG217](https://user-images.githubusercontent.com/7161204/65448670-f8e2f080-de6b-11e9-9d77-7c95e0d4348f.jpeg)
The phone needs to open an app auto-start switch

**Comment by bertvandepoel** [comment] 2019-09-23 17:40
@maxiaoping If this is a response to mee: the auto-start switch is on. I specifically went into that menu to force a sync now. As you can see in the thread above, people are quite aware of this fact. We're quite sure this has something to do with the size of the library.

**Comment by maxiaoping** [comment] 2019-09-23 17:47
<img width="943" alt="WX20190924" src="https://user-images.githubusercontent.com/7161204/65449240-25e3d300-de6d-11e9-8e56-5772fd761eb4.png">

**Comment by maxiaoping** [comment] 2019-09-23 17:52
> @maxiaoping If this is a response to me: the auto-start switch is on. I specifically went into that menu to force a sync now. As you can see in the thread above, people are quite aware of this fact. We're quite sure this has something to do with the size of the gallery.

I tried to test the problem

**Comment by bertvandepoel** [comment] 2019-09-23 17:54
I see, so you also have the problem? Could you learn something from the log?

**Comment by maxiaoping** [comment] 2019-09-23 17:59
> I see, so you also have the problem? Could you learn something from the log?

My gallery photo is limited, so I can't test this problem temporarily，but I tried to test the problem

**Comment by bertvandepoel** [comment] 2019-09-23 18:05
@maxiaoping 
We've found that the problem has to do with the size of the gallery. I was able to sync a few months ago when I deleted a load of picture (but like, hundreds) and forced "sync now" a lot of times. Since then I've not been able to do a decent sync though, which is problematic. I was hoping to help with the logs, but the contents don't seem to help. 

I can verify that automatic synchronization is on by the way, if that's a question you have. 

To give you an idea of size, I have 5800 pictures and 49 videos on my phone. Not all of those are synced through Seafile, but most are. So maybe it's worth taking 2000+ pictures or something, and then see if the problem starts happening to you. @framps had 1216 pictures by the way.

**Comment by nazco** [comment] 2019-09-23 22:56
I've 3408 pictures in the gallery that should be synced, but the problems started a lot earlier.

**Comment by c3rebro** [comment] 2019-10-06 20:26
Hello together. Iam facing issues on that topic too.
I updated to seafile server 7.0.5 recently and have Android 9.0 running. Seadroid is 2.2.18.

It seems that i have that issue since my old Galaxy has been broken and i changed to my new Galaxy S8 but iam not sure.

To be more specifically about that issue: I ONLY facing issues when trying to upload videos or larger Files. Pictures are uploaded fine. I guess that video sizes above apr. 30MiB causes the auto upload feature to fail. I just tested the following: If i cancel all auto-uploads and re-setup them. i have 52 Files with 22GB in my Upload queue. The first two with apr. 73MB each fails as soon as they reach about 90%. 

BUT: When i switch off the auto-upload feature and select all of the files manually they got uploaded fine. Even the 2GB Videos. It also does not matter if the phone goes to sleep and turns the display off. It just doesnt stop uploading if startet manually.

Any ideas? Where can i find the logs btw? Andoid 9 does not seem to have a /emulated/0/ directory does it?

**Comment by yhtang** [comment] 2019-12-04 00:11
> I get this problem all the time. I just checked now and it hadn't synced since March. I'm on the latest version. I got it syncing again by disabling and reenabling syncing, but then of course as described in #815 it reuploads all deleted images. It's really quite weird and inconvenient that this works fine on Dropbox but not on Seafile, I switched to Seafile because I wanted to move away from proprietary commercial software like Dropbox but Seadroid is proving a struggle. The server and client are great though, love them :)

I have exactly the same situation here :cry:

**Comment by freeplant** [comment] 2019-12-04 00:53
The next release will contain a fix. And the status of syncing will be shown in the UI.

**Comment by yhtang** [comment] 2019-12-07 08:44
> The next release will contain a fix. And the status of syncing will be shown in the UI.

Oh. That's great news! Thanks!

**Comment by freeplant** [comment] 2019-12-16 02:05
The new version 2.2.22 can be download in https://github.com/haiwen/seadroid/releases

**Comment by bertvandepoel** [comment] 2019-12-16 02:42
Will it release on the play store as well, or is this a beta release for testing?

**Comment by freeplant** [comment] 2019-12-17 05:34
This is beta release for testing.

**Comment by freeplant** [comment] 2020-01-08 06:57
The problem should have been fixed.

**Closed by freeplant** 2020-01-08 06:57 UTC

**Comment by bertvandepoel** [comment] 2020-01-08 14:30
Just wanted to quickly let you know I just tried out 2.2.25 from the play store and it managed my backlog of about 1000 images and videos. This is great news. Thank you very much for fixing this issue :smiley:

**Comment by nazco** [comment] 2020-01-08 17:48
Works here too! Thanks for the fix!

**Comment by framps** [comment] 2020-01-08 19:32
Works perfect for me too. Great work :+1:

**Comment by sosnicki** [comment] 2020-01-09 11:19
Thank you very much! It works like a charm.

**Comment by yhtang** [comment] 2020-01-09 23:27
I can confirm that the problem is gone on Huawei P30 Pro with EMUI 9. Thanks!

**Comment by toasterking** [comment] 2020-01-09 23:46
I've been having both problems (automatic sync does not trigger; manual sync fails) for many months on BlackBerry PRIV running Android 6.  I've played around with battery and data saver settings and nginx on my server.  I just looked into troubleshooting it again and was amazed to find I just barely missed the bugfixed version when I updated apps a couple of days ago.  Both problems are fixed for me now with 2.2.25.  Thank you very much!!
