### ISSUE TITLE
Uploading not working at all in 2.2.2, and no error shown

### ISSUE THREAD

**Issue by 80tf3262p8** [haiwen/seadroid#730] opened 2018-03-28 07:07 UTC
Uploads aren't working in 2.2.2 (F-Droid version, at least). I tried clearing data and clean reinstalling 2.2.2 multiple times. Creating (via Seafile) and editing a new text document, changes don't result in a successful upload. Document stays at 0kb and reopening shows it empty. Same for Keepass2Android databases; unfortunately I lost changes due to this.

This affects both attempting to open a file through Seafile itself or through the storage facility. Manual uploads don't work either, although they appear to. New file uploads don't actually appear. I can try to upload a file and replace an existing one and it asks to overwrite, and it says it updated, but no change occurs.

No error is reported by the app! The files on the server simply don't get changed, and their modification dates don't change either.

Reverted to clean install of Seafile F-Droid version 2.2.1 from December and the described tests work as expected.

Server was 6.2.4; updated to 6.2.5 and no fix. (x64, Ubuntu 17.10)

**Comment by 80tf3262p8** [comment] 2018-03-30 18:29
(Maybe this is what entirely broke uploads: https://github.com/haiwen/seadroid/commit/07c94f268b8ad2fbfd9ffd1f57c7dcb06f2dd0ed )

**Comment by ERamseth** [comment] 2018-03-31 15:00
Seeing same issue. 2.2.1 works fine

**Comment by SirLaffalot** [comment] 2018-04-15 01:39
Same here: Open keepassx database from the Seafile browser, modify one entry, close out back to Seafile browser - the file does not get transferred to the server.

In aLogcat: the log show D/SeafileObserver: ......./SomePwSafe.kdbx was modified!
However, still no upload. The server is not updated.

**Comment by SirLaffalot** [comment] 2018-04-15 03:55
I downgraded to 2.2.1 and it works perfectly there.

**Comment by 80tf3262p8** [comment] 2018-04-15 19:43
Upgraded from 2.2.1 to 2.2.3 to test, and here I can upload *new* files, which is different from the behavior I initially reported about 2.2.2 (assuming that was fully accurate), but I still cannot change files. Replacing/updating existing files still does not actually change the files, all as initially reported.
This is honestly one of the most severe bugs an app like this can have, so I wish it would get some attention.

**Comment by RoestVrijStaal** [comment] 2018-05-05 15:27
Bump, I'm also having this issue.

And because the webclient lacks a Responsive/Mobile layout it's getting very annoying.

**Comment by 80tf3262p8** [comment] 2018-05-30 04:58
I wiped my phone and reinstalled Seafile, having forgotten about this issue, and of course uploads were still completely broken in the latest version.
Hello??? Is anyone out there?

**Comment by freeplant** [comment] 2018-05-30 05:02
We are rewriting the uploading related code to solve several issues, this will take time. You can use the version in Google PlayStore which can work.

**Comment by 80tf3262p8** [comment] 2018-05-30 05:09
Is there a reason not to revert the broken builds in F-Droid, other than the user base being small enough not to care? New users won't know they need to install an older version and not everyone even has the Play Store.

**Comment by freeplant** [comment] 2018-06-06 05:47
We have uploaded version 2.2.4 to GitHub. Can you try if you still have the upload problem?

**Comment by RoestVrijStaal** [comment] 2018-06-07 16:17
Can't truly verify since the phone which produced the issue is send for repair for a new screen. 

But it works for my very old replacement phone.

**Comment by SirLaffalot** [comment] 2018-06-09 12:42
Working on one of my phones. I tried adding a file (share/send to), and editing a file and both were transferred from phone to server.

I will try second phone later.

First phone is:

OnePlus One running
ResurrectionRemix 
Android Nougat 7.1.2

Ivan

On June 6, 2018 1:47:27 AM EDT, Daniel Pan <notifications@github.com> wrote:
>We have uploaded version 2.2.4 to GitHub. Can you try if you still have
>the upload problem?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/haiwen/seadroid/issues/730#issuecomment-394947647

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2018-06-14 03:35 UTC
Labels: maybe-bug

**Comment by RoestVrijStaal** [comment] 2018-09-03 21:26
Update:

I got my daily driver back (Android 7). 

It works again.
