### ISSUE TITLE
Enter settings, software crash

### ISSUE THREAD

**Issue by darlexlin** [haiwen/seadroid#892] opened 2021-05-11 04:08 UTC
1、Enter settings, software crash
2、Synchronization cannot be performed

**Comment by atomdmac** [comment] 2021-05-16 14:14
Seeing the crash on Pixel 2 on Android 11.  Syncing continues to work, however.

**Comment by DPTJKKVH** [comment] 2021-05-18 13:11
This is a duplicate of #874 . Please post your logcat excerpts there.

**Comment by fabian-z** [comment] 2021-05-20 00:47
The settings and sync work for me on Android 11 after moving a null check - if you are affected, please test my fix in #894.

I am not sure if this is in fact a duplicate of #874, since there are different logcats in this issue and no logs are posted here.

**Comment by maxiaoping** [comment] 2021-07-02 03:53
Please update the latest version

**Comment by darlexlin** [comment] 2021-07-02 03:55
The latest version is ok.

**Closed** 2021-07-02 06:45 UTC
